//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_I102.ServiceReferenceTerrasoft {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.terrasoft.ru/", ConfigurationName="ServiceReferenceTerrasoft.ExternalServiceSoap")]
    public interface ExternalServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/UploadApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        Test_I102.ServiceReferenceTerrasoft.Response UploadApplication(Test_I102.ServiceReferenceTerrasoft.GenericApplication request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/UploadApplication", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.Response> UploadApplicationAsync(Test_I102.ServiceReferenceTerrasoft.GenericApplication request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/SetApplicationParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        Test_I102.ServiceReferenceTerrasoft.ParameterResponce SetApplicationParameters(Test_I102.ServiceReferenceTerrasoft.ApplicationParameterToChoose request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/SetApplicationParameters", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.ParameterResponce> SetApplicationParametersAsync(Test_I102.ServiceReferenceTerrasoft.ApplicationParameterToChoose request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/GetApplicationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        Test_I102.ServiceReferenceTerrasoft.ApplicationStatusResponse GetApplicationStatus(Test_I102.ServiceReferenceTerrasoft.ApplicationStatusRequest request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.terrasoft.ru/GetApplicationStatus", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.ApplicationStatusResponse> GetApplicationStatusAsync(Test_I102.ServiceReferenceTerrasoft.ApplicationStatusRequest request, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class GenericApplication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GenericInfo genericInfoField;
        
        private DepositInfo depositInfoField;
        
        private CreditInfo creditInfoField;
        
        private RegistrationDocument registrationDocumentField;
        
        private Addresses addressesField;
        
        private Communications communicationsField;
        
        private Employer employerField;
        
        private EarlierAppointedCredit[] earlierAppointedCreditsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GenericInfo GenericInfo {
            get {
                return this.genericInfoField;
            }
            set {
                this.genericInfoField = value;
                this.RaisePropertyChanged("GenericInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DepositInfo DepositInfo {
            get {
                return this.depositInfoField;
            }
            set {
                this.depositInfoField = value;
                this.RaisePropertyChanged("DepositInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CreditInfo CreditInfo {
            get {
                return this.creditInfoField;
            }
            set {
                this.creditInfoField = value;
                this.RaisePropertyChanged("CreditInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RegistrationDocument RegistrationDocument {
            get {
                return this.registrationDocumentField;
            }
            set {
                this.registrationDocumentField = value;
                this.RaisePropertyChanged("RegistrationDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Addresses Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Communications Communications {
            get {
                return this.communicationsField;
            }
            set {
                this.communicationsField = value;
                this.RaisePropertyChanged("Communications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Employer Employer {
            get {
                return this.employerField;
            }
            set {
                this.employerField = value;
                this.RaisePropertyChanged("Employer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public EarlierAppointedCredit[] EarlierAppointedCredits {
            get {
                return this.earlierAppointedCreditsField;
            }
            set {
                this.earlierAppointedCreditsField = value;
                this.RaisePropertyChanged("EarlierAppointedCredits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class GenericInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ApplicationTypes applicationTypeField;
        
        private string nameField;
        
        private string paternalNameField;
        
        private string lastNameField;
        
        private string genderField;
        
        private string citizenshipField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string placeOfBirthField;
        
        private System.Nullable<bool> isNotPublicPersonField;
        
        private System.Nullable<bool> isAgreeAuthorityTransferField;
        
        private System.Nullable<bool> isDataAuthenticField;
        
        private string iNNField;
        
        private string sMScodeField;
        
        private bool isAgreeInsurance1Field;
        
        private bool isAgreeInsurance2Field;
        
        private bool isAgreeInsurance3Field;
        
        private string firstNameRomanTypeField;
        
        private string secondNameRomanTypeField;
        
        private string cardCategoryField;
        
        private System.DateTime registrationDateOnAddressField;
        
        private bool isRegEqualFactAddressField;
        
        private bool isSecondNameNOTChangedField;
        
        private string previousSecondNameField;
        
        private string contactPhoneField;
        
        private string contactNameField;
        
        private string relationDegreeField;
        
        private string secretWordField;
        
        private string maidenNameField;
        
        private string secretQuestionField;
        
        private string privateSecretQuestionField;
        
        private string secretQuestionAnswerField;
        
        private string tPinField;
        
        private string bankingServiceField;
        
        private string currencyAskedField;
        
        private string userIPField;
        
        private string trafficSourceField;
        
        private string trafficTypeField;
        
        private string advertContentField;
        
        private string contentAdvertKeyWordField;
        
        private string advertCompanyProductField;
        
        private string pageAddressField;
        
        private string partnerMarkField;
        
        private string clientTypeField;
        
        private System.DateTime fillingStartDateField;
        
        private System.DateTime sendingDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ApplicationTypes ApplicationType {
            get {
                return this.applicationTypeField;
            }
            set {
                this.applicationTypeField = value;
                this.RaisePropertyChanged("ApplicationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PaternalName {
            get {
                return this.paternalNameField;
            }
            set {
                this.paternalNameField = value;
                this.RaisePropertyChanged("PaternalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
                this.RaisePropertyChanged("Citizenship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
                this.RaisePropertyChanged("PlaceOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsNotPublicPerson {
            get {
                return this.isNotPublicPersonField;
            }
            set {
                this.isNotPublicPersonField = value;
                this.RaisePropertyChanged("IsNotPublicPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsAgreeAuthorityTransfer {
            get {
                return this.isAgreeAuthorityTransferField;
            }
            set {
                this.isAgreeAuthorityTransferField = value;
                this.RaisePropertyChanged("IsAgreeAuthorityTransfer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<bool> IsDataAuthentic {
            get {
                return this.isDataAuthenticField;
            }
            set {
                this.isDataAuthenticField = value;
                this.RaisePropertyChanged("IsDataAuthentic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SMScode {
            get {
                return this.sMScodeField;
            }
            set {
                this.sMScodeField = value;
                this.RaisePropertyChanged("SmsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsAgreeInsurance1 {
            get {
                return this.isAgreeInsurance1Field;
            }
            set {
                this.isAgreeInsurance1Field = value;
                this.RaisePropertyChanged("IsAgreeInsurance1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsAgreeInsurance2 {
            get {
                return this.isAgreeInsurance2Field;
            }
            set {
                this.isAgreeInsurance2Field = value;
                this.RaisePropertyChanged("IsAgreeInsurance2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsAgreeInsurance3 {
            get {
                return this.isAgreeInsurance3Field;
            }
            set {
                this.isAgreeInsurance3Field = value;
                this.RaisePropertyChanged("IsAgreeInsurance3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string FirstNameRomanType {
            get {
                return this.firstNameRomanTypeField;
            }
            set {
                this.firstNameRomanTypeField = value;
                this.RaisePropertyChanged("FirstNameRomanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string SecondNameRomanType {
            get {
                return this.secondNameRomanTypeField;
            }
            set {
                this.secondNameRomanTypeField = value;
                this.RaisePropertyChanged("SecondNameRomanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CardCategory {
            get {
                return this.cardCategoryField;
            }
            set {
                this.cardCategoryField = value;
                this.RaisePropertyChanged("CardCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime RegistrationDateOnAddress {
            get {
                return this.registrationDateOnAddressField;
            }
            set {
                this.registrationDateOnAddressField = value;
                this.RaisePropertyChanged("RegistrationDateOnAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool IsRegEqualFactAddress {
            get {
                return this.isRegEqualFactAddressField;
            }
            set {
                this.isRegEqualFactAddressField = value;
                this.RaisePropertyChanged("IsRegEqualFactAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool IsSecondNameNOTChanged {
            get {
                return this.isSecondNameNOTChangedField;
            }
            set {
                this.isSecondNameNOTChangedField = value;
                this.RaisePropertyChanged("IsSecondNameNOTChanged");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PreviousSecondName {
            get {
                return this.previousSecondNameField;
            }
            set {
                this.previousSecondNameField = value;
                this.RaisePropertyChanged("PreviousSecondName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string ContactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("ContactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("ContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string RelationDegree {
            get {
                return this.relationDegreeField;
            }
            set {
                this.relationDegreeField = value;
                this.RaisePropertyChanged("RelationDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string SecretWord {
            get {
                return this.secretWordField;
            }
            set {
                this.secretWordField = value;
                this.RaisePropertyChanged("SecretWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string MaidenName {
            get {
                return this.maidenNameField;
            }
            set {
                this.maidenNameField = value;
                this.RaisePropertyChanged("MaidenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SecretQuestion {
            get {
                return this.secretQuestionField;
            }
            set {
                this.secretQuestionField = value;
                this.RaisePropertyChanged("SecretQuestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PrivateSecretQuestion {
            get {
                return this.privateSecretQuestionField;
            }
            set {
                this.privateSecretQuestionField = value;
                this.RaisePropertyChanged("PrivateSecretQuestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SecretQuestionAnswer {
            get {
                return this.secretQuestionAnswerField;
            }
            set {
                this.secretQuestionAnswerField = value;
                this.RaisePropertyChanged("SecretQuestionAnswer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string TPin {
            get {
                return this.tPinField;
            }
            set {
                this.tPinField = value;
                this.RaisePropertyChanged("TPin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string BankingService {
            get {
                return this.bankingServiceField;
            }
            set {
                this.bankingServiceField = value;
                this.RaisePropertyChanged("BankingService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string CurrencyAsked {
            get {
                return this.currencyAskedField;
            }
            set {
                this.currencyAskedField = value;
                this.RaisePropertyChanged("CurrencyAsked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string UserIP {
            get {
                return this.userIPField;
            }
            set {
                this.userIPField = value;
                this.RaisePropertyChanged("UserIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string TrafficSource {
            get {
                return this.trafficSourceField;
            }
            set {
                this.trafficSourceField = value;
                this.RaisePropertyChanged("TrafficSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string TrafficType {
            get {
                return this.trafficTypeField;
            }
            set {
                this.trafficTypeField = value;
                this.RaisePropertyChanged("TrafficType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string AdvertContent {
            get {
                return this.advertContentField;
            }
            set {
                this.advertContentField = value;
                this.RaisePropertyChanged("AdvertContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string ContentAdvertKeyWord {
            get {
                return this.contentAdvertKeyWordField;
            }
            set {
                this.contentAdvertKeyWordField = value;
                this.RaisePropertyChanged("ContentAdvertKeyWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string AdvertCompanyProduct {
            get {
                return this.advertCompanyProductField;
            }
            set {
                this.advertCompanyProductField = value;
                this.RaisePropertyChanged("AdvertCompanyProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string PageAddress {
            get {
                return this.pageAddressField;
            }
            set {
                this.pageAddressField = value;
                this.RaisePropertyChanged("PageAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string PartnerMark {
            get {
                return this.partnerMarkField;
            }
            set {
                this.partnerMarkField = value;
                this.RaisePropertyChanged("PartnerMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ClientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
                this.RaisePropertyChanged("ClientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public System.DateTime FillingStartDate {
            get {
                return this.fillingStartDateField;
            }
            set {
                this.fillingStartDateField = value;
                this.RaisePropertyChanged("FillingStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public System.DateTime SendingDateTime {
            get {
                return this.sendingDateTimeField;
            }
            set {
                this.sendingDateTimeField = value;
                this.RaisePropertyChanged("SendingDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public enum ApplicationTypes {
        
        /// <remarks/>
        credit,
        
        /// <remarks/>
        deposit,
        
        /// <remarks/>
        ets,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class ApplicationStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response resultField;
        
        private string idApplicationField;
        
        private string statusField;
        
        private string textField;
        
        private Result[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdApplication {
            get {
                return this.idApplicationField;
            }
            set {
                this.idApplicationField = value;
                this.RaisePropertyChanged("IdApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Result[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccessField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class ApplicationStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telField;
        
        private string smsCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string smsCode {
            get {
                return this.smsCodeField;
            }
            set {
                this.smsCodeField = value;
                this.RaisePropertyChanged("smsCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class ParameterResponce : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class ApplicationParameterToChoose : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationNumberField;
        
        private string parameterGroupNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationNumber {
            get {
                return this.applicationNumberField;
            }
            set {
                this.applicationNumberField = value;
                this.RaisePropertyChanged("ApplicationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParameterGroupNumber {
            get {
                return this.parameterGroupNumberField;
            }
            set {
                this.parameterGroupNumberField = value;
                this.RaisePropertyChanged("ParameterGroupNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class EarlierAppointedCredit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankField;
        
        private string creditTypeField;
        
        private string statusField;
        
        private System.DateTime openDateField;
        
        private string currencyField;
        
        private decimal creditLimitField;
        
        private string maxLoanTermField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
                this.RaisePropertyChanged("Bank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CreditType {
            get {
                return this.creditTypeField;
            }
            set {
                this.creditTypeField = value;
                this.RaisePropertyChanged("CreditType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
                this.RaisePropertyChanged("OpenDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
                this.RaisePropertyChanged("CreditLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaxLoanTerm {
            get {
                return this.maxLoanTermField;
            }
            set {
                this.maxLoanTermField = value;
                this.RaisePropertyChanged("MaxLoanTerm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Employer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNameField;
        
        private string accountTypeField;
        
        private string laborContractTypeField;
        
        private string accountSphereField;
        
        private string totalWorkExperienceField;
        
        private string lastSeniorityField;
        
        private string jobTitleField;
        
        private string accountCompanySiteField;
        
        private string accountCompanyEmployeesQtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LaborContractType {
            get {
                return this.laborContractTypeField;
            }
            set {
                this.laborContractTypeField = value;
                this.RaisePropertyChanged("LaborContractType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string AccountSphere {
            get {
                return this.accountSphereField;
            }
            set {
                this.accountSphereField = value;
                this.RaisePropertyChanged("AccountSphere");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TotalWorkExperience {
            get {
                return this.totalWorkExperienceField;
            }
            set {
                this.totalWorkExperienceField = value;
                this.RaisePropertyChanged("TotalWorkExperience");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string LastSeniority {
            get {
                return this.lastSeniorityField;
            }
            set {
                this.lastSeniorityField = value;
                this.RaisePropertyChanged("LastSeniority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
                this.RaisePropertyChanged("JobTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AccountCompanySite {
            get {
                return this.accountCompanySiteField;
            }
            set {
                this.accountCompanySiteField = value;
                this.RaisePropertyChanged("AccountCompanySite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AccountCompanyEmployeesQty {
            get {
                return this.accountCompanyEmployeesQtyField;
            }
            set {
                this.accountCompanyEmployeesQtyField = value;
                this.RaisePropertyChanged("AccountCompanyEmployeesQty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Communication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Communications : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Communication workPhoneField;
        
        private Communication addPhoneField;
        
        private Communication mainPhoneField;
        
        private Communication homePhoneField;
        
        private Communication mobilePhoneField;
        
        private Communication mailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Communication workPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("workPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Communication addPhone {
            get {
                return this.addPhoneField;
            }
            set {
                this.addPhoneField = value;
                this.RaisePropertyChanged("addPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Communication mainPhone {
            get {
                return this.mainPhoneField;
            }
            set {
                this.mainPhoneField = value;
                this.RaisePropertyChanged("mainPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Communication homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("homePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public Communication mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("mobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public Communication mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lineCodeKLADRField;
        
        private string countryField;
        
        private string zipField;
        
        private string oKATOField;
        
        private string streetField;
        
        private string streetTypeField;
        
        private string buildingField;
        
        private string building2Field;
        
        private string building3Field;
        
        private string officeField;
        
        private string apartmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LineCodeKLADR {
            get {
                return this.lineCodeKLADRField;
            }
            set {
                this.lineCodeKLADRField = value;
                this.RaisePropertyChanged("LineCodeKLADR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OKATO {
            get {
                return this.oKATOField;
            }
            set {
                this.oKATOField = value;
                this.RaisePropertyChanged("OKATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Building2 {
            get {
                return this.building2Field;
            }
            set {
                this.building2Field = value;
                this.RaisePropertyChanged("Building2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Building3 {
            get {
                return this.building3Field;
            }
            set {
                this.building3Field = value;
                this.RaisePropertyChanged("Building3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("Office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
                this.RaisePropertyChanged("Apartment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class Addresses : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Address registrationAddressField;
        
        private Address factAddressField;
        
        private Address workAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address RegistrationAddress {
            get {
                return this.registrationAddressField;
            }
            set {
                this.registrationAddressField = value;
                this.RaisePropertyChanged("RegistrationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address FactAddress {
            get {
                return this.factAddressField;
            }
            set {
                this.factAddressField = value;
                this.RaisePropertyChanged("FactAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Address WorkAddress {
            get {
                return this.workAddressField;
            }
            set {
                this.workAddressField = value;
                this.RaisePropertyChanged("WorkAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class RegistrationDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentSeriesField;
        
        private string documentNumberField;
        
        private System.Nullable<System.DateTime> issuedOnField;
        
        private string issuedPlaceField;
        
        private string issuedByField;
        
        private string issueCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string DocumentSeries {
            get {
                return this.documentSeriesField;
            }
            set {
                this.documentSeriesField = value;
                this.RaisePropertyChanged("DocumentSeries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> IssuedOn {
            get {
                return this.issuedOnField;
            }
            set {
                this.issuedOnField = value;
                this.RaisePropertyChanged("IssuedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string IssuedPlace {
            get {
                return this.issuedPlaceField;
            }
            set {
                this.issuedPlaceField = value;
                this.RaisePropertyChanged("IssuedPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string IssuedBy {
            get {
                return this.issuedByField;
            }
            set {
                this.issuedByField = value;
                this.RaisePropertyChanged("IssuedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string IssueCode {
            get {
                return this.issueCodeField;
            }
            set {
                this.issueCodeField = value;
                this.RaisePropertyChanged("IssueCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class CreditInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maritalStatusField;
        
        private string minorChildrenNumberField;
        
        private string dependentsNumberField;
        
        private string educationField;
        
        private System.Nullable<bool> isAgreePersonalDataField;
        
        private System.Nullable<decimal> creditLimitAskedField;
        
        private int creditTermAskedField;
        
        private string deliveryAddressField;
        
        private decimal creditOutgoField;
        
        private decimal otherOutgoField;
        
        private decimal averageMonthlyPartnerIncomeField;
        
        private string previousCreditsQuantityField;
        
        private string creditPurposeField;
        
        private System.Nullable<decimal> averageMonthlyIncomeField;
        
        private string incomeCheckStatusField;
        
        private bool isBankClientField;
        
        private bool isBankWorkerField;
        
        private bool isDepositOwnerField;
        
        private bool isSalaryProjectClientField;
        
        private string militaryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("MaritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MinorChildrenNumber {
            get {
                return this.minorChildrenNumberField;
            }
            set {
                this.minorChildrenNumberField = value;
                this.RaisePropertyChanged("MinorChildrenNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DependentsNumber {
            get {
                return this.dependentsNumberField;
            }
            set {
                this.dependentsNumberField = value;
                this.RaisePropertyChanged("DependentsNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Education {
            get {
                return this.educationField;
            }
            set {
                this.educationField = value;
                this.RaisePropertyChanged("Education");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> IsAgreePersonalData {
            get {
                return this.isAgreePersonalDataField;
            }
            set {
                this.isAgreePersonalDataField = value;
                this.RaisePropertyChanged("IsAgreePersonalData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> CreditLimitAsked {
            get {
                return this.creditLimitAskedField;
            }
            set {
                this.creditLimitAskedField = value;
                this.RaisePropertyChanged("CreditLimitAsked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CreditTermAsked {
            get {
                return this.creditTermAskedField;
            }
            set {
                this.creditTermAskedField = value;
                this.RaisePropertyChanged("CreditTermAsked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DeliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
                this.RaisePropertyChanged("DeliveryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal CreditOutgo {
            get {
                return this.creditOutgoField;
            }
            set {
                this.creditOutgoField = value;
                this.RaisePropertyChanged("CreditOutgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal OtherOutgo {
            get {
                return this.otherOutgoField;
            }
            set {
                this.otherOutgoField = value;
                this.RaisePropertyChanged("OtherOutgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal AverageMonthlyPartnerIncome {
            get {
                return this.averageMonthlyPartnerIncomeField;
            }
            set {
                this.averageMonthlyPartnerIncomeField = value;
                this.RaisePropertyChanged("AverageMonthlyPartnerIncome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PreviousCreditsQuantity {
            get {
                return this.previousCreditsQuantityField;
            }
            set {
                this.previousCreditsQuantityField = value;
                this.RaisePropertyChanged("PreviousCreditsQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CreditPurpose {
            get {
                return this.creditPurposeField;
            }
            set {
                this.creditPurposeField = value;
                this.RaisePropertyChanged("CreditPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> AverageMonthlyIncome {
            get {
                return this.averageMonthlyIncomeField;
            }
            set {
                this.averageMonthlyIncomeField = value;
                this.RaisePropertyChanged("AverageMonthlyIncome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string IncomeCheckStatus {
            get {
                return this.incomeCheckStatusField;
            }
            set {
                this.incomeCheckStatusField = value;
                this.RaisePropertyChanged("IncomeCheckStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsBankClient {
            get {
                return this.isBankClientField;
            }
            set {
                this.isBankClientField = value;
                this.RaisePropertyChanged("IsBankClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsBankWorker {
            get {
                return this.isBankWorkerField;
            }
            set {
                this.isBankWorkerField = value;
                this.RaisePropertyChanged("IsBankWorker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsDepositOwner {
            get {
                return this.isDepositOwnerField;
            }
            set {
                this.isDepositOwnerField = value;
                this.RaisePropertyChanged("IsDepositOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsSalaryProjectClient {
            get {
                return this.isSalaryProjectClientField;
            }
            set {
                this.isSalaryProjectClientField = value;
                this.RaisePropertyChanged("IsSalaryProjectClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string MilitaryStatus {
            get {
                return this.militaryStatusField;
            }
            set {
                this.militaryStatusField = value;
                this.RaisePropertyChanged("MilitaryStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.terrasoft.ru/")]
    public partial class DepositInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> depositLimitAskedField;
        
        private int depositTermAskedField;
        
        private string percentPaymentMethodField;
        
        private string percentPaymentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> DepositLimitAsked {
            get {
                return this.depositLimitAskedField;
            }
            set {
                this.depositLimitAskedField = value;
                this.RaisePropertyChanged("DepositLimitAsked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DepositTermAsked {
            get {
                return this.depositTermAskedField;
            }
            set {
                this.depositTermAskedField = value;
                this.RaisePropertyChanged("DepositTermAsked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PercentPaymentMethod {
            get {
                return this.percentPaymentMethodField;
            }
            set {
                this.percentPaymentMethodField = value;
                this.RaisePropertyChanged("PercentPaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PercentPayment {
            get {
                return this.percentPaymentField;
            }
            set {
                this.percentPaymentField = value;
                this.RaisePropertyChanged("PercentPayment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternalServiceSoapChannel : Test_I102.ServiceReferenceTerrasoft.ExternalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalServiceSoapClient : System.ServiceModel.ClientBase<Test_I102.ServiceReferenceTerrasoft.ExternalServiceSoap>, Test_I102.ServiceReferenceTerrasoft.ExternalServiceSoap {
        
        public ExternalServiceSoapClient() {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Test_I102.ServiceReferenceTerrasoft.Response UploadApplication(Test_I102.ServiceReferenceTerrasoft.GenericApplication request, string password) {
            return base.Channel.UploadApplication(request, password);
        }
        
        public System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.Response> UploadApplicationAsync(Test_I102.ServiceReferenceTerrasoft.GenericApplication request, string password) {
            return base.Channel.UploadApplicationAsync(request, password);
        }
        
        public Test_I102.ServiceReferenceTerrasoft.ParameterResponce SetApplicationParameters(Test_I102.ServiceReferenceTerrasoft.ApplicationParameterToChoose request, string password) {
            return base.Channel.SetApplicationParameters(request, password);
        }
        
        public System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.ParameterResponce> SetApplicationParametersAsync(Test_I102.ServiceReferenceTerrasoft.ApplicationParameterToChoose request, string password) {
            return base.Channel.SetApplicationParametersAsync(request, password);
        }
        
        public Test_I102.ServiceReferenceTerrasoft.ApplicationStatusResponse GetApplicationStatus(Test_I102.ServiceReferenceTerrasoft.ApplicationStatusRequest request, string password) {
            return base.Channel.GetApplicationStatus(request, password);
        }
        
        public System.Threading.Tasks.Task<Test_I102.ServiceReferenceTerrasoft.ApplicationStatusResponse> GetApplicationStatusAsync(Test_I102.ServiceReferenceTerrasoft.ApplicationStatusRequest request, string password) {
            return base.Channel.GetApplicationStatusAsync(request, password);
        }
    }
}
